name: Gneiss-Building-Bulgaria
description: Gneiss Building Bulgaria. Official Website. Rocks today.

base.url: https://siksites.github.io # the subpath of your site, e.g. /blog
url: /gbb

permalink: :title/

markdown: kramdown
highlight: rouge
paginate: 10


sass:
  style: compressed

include: [_pages]

gems: [jekyll-paginate]

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
